SkillsFundingAgency/das-employercommitments-v2

azure-pipelines.yml
This PR is to merge the initial azure-pipelines.yml build file.
=> Initial azure-pipelines.yml build file

azure-pipelines.yml
Added a DotNetCoreCLI task to perform unit tests.
=> Added a DotNetCoreCLI task to perform unit tests.

azure/template.json
This is the initial ARM template to deploy the following resources:
- App Service Plan
- App Service Certificate
- App Service
- App Insights
=> Added initial ARM template

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/CreateCohort/Assign.cshtml
282 was targetted at 232 for merge, PR to get 282 into master.
=> Pr to merge CV-282 into master

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/DetailsViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Models/CohortDraftApprenticeshipViewModelTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/DraftApprenticeshipController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/DetailsViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/DetailsViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/SFA.DAS.EmployerCommitmentsV2.Web.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Startup/AspNetStartup.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Startup/MvcStartup.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Cohort/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2/SFA.DAS.EmployerCommitmentsV2.csproj
📢 PR is against CV-17 for diff purposes, and should be pointed to master for merging.
=> Cv 19 add apprentice details to cohort page

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/DetailsViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/DetailsViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Cohort/Details.cshtml
📢 Merge target is CV-19 for diff purposes as branched from here. Should retarget to master for merging.
=> CV-18 Adds edit link to cohort details page for each app

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Cohort/Details.cshtml
Still waiting for James King to give us the layout for the LHS/RHS add and delete links
=> Cv 403 delete this group

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/CohortControllerTests/WhenGettingApproval.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/ApprovedViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/SentViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/CohortController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/ApprovedViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/DetailsViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/ApprovedRequest.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/ApprovedViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Cohort/Approved.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_Layout.cshtml
📢 Based off CV-380
Also depends upon CV-395 on the api in order for the transfer scenario to be testable.
=> Cv 381 approval confirmation

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Validators/ApprenticeViewModelValidatorTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Validators/ApprenticeViewModelValidator.cs
Date validation added to align the behavior with Edit draft apprenticeship.
=> CV-549 Date Validation added

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/ManageApprenticesTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Cookies/CookieNames.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/DependencyResolution/WebRegistry.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/IndexRequest.cs
Now we can retrieve store search requests from cookie storage when required
=> MF 488 - Added cookie storage to manage page

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Home/Index.cshtml
Updates content on the homepage
=> CON-2006 updates content to remove references to cohort

src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/RouteValues/RouteNames.cs
I have also updated the v1 details page link to point to the new inform page url
https://github.com/SkillsFundingAgency/das-employercommitments/pull/276
=> CON-2619 Update page urls

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenCallingApprenticeshipDetailsTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenPostingEditEndDateTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_FlashMessagePartial.cshtml
Added flash message for AC6 - edit planned end date.
=> Con 3390 apprentice details flash banners

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ReviewApprenticeshipUpdatesRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ReviewApprenticeshipUpdatesRequestToViewModelMapper.cs
Unit tests are work in progress.
=> CON-3569 Added fix to model mapper

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ConfirmEditApprenticeshipRequestToConfirmEditViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/EditApprenticeshipRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ReviewApprenticeshipUpdatesRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ViewApprenticehipUpdatesRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ConfirmEditApprenticehsipViewModelToEditApiRequestMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ConfirmEditApprenticeshipRequestToConfirmEditViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/EditApprenticeshipRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/EditApprenticeshipViewModelToValidateApprenticeshipForEditMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ReviewApprenticeshipUpdatesRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ViewApprenticehipUpdatesRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/ApprenticeshipDetailsRequestViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/Edit/BaseEdit.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/Edit/EditApprenticeshipRequestViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/SFA.DAS.EmployerCommitmentsV2.Web.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ApprenticeshipUpdatesPartial/_ViewApprenticeshipUpdates.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ConfirmEditApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/EditApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Index.cshtml
Cs 788 employer edit email address web
=> Cs 788 employer edit email address web

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ApprenticeshipDetailsToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/DetailsViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/DetailsViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/DetailsViewCourseGroupingModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/DetailsViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/EmailOverlapsModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/SFA.DAS.EmployerCommitmentsV2.Web.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Cohort/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2/SFA.DAS.EmployerCommitmentsV2.csproj
Cmad approvals changes employer merge 866 & 1030
=> Cmad approvals changes employer

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/IndexViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Models/ApprenticeFilterModelTests/WhenGettingRouteData.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/IndexViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/ApprenticesFilterModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/IndexRequest.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/SFA.DAS.EmployerCommitmentsV2.Web.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Index.cshtml
CS-893-ConfirmationStatusFilter initial checkin
=> CS-893-ConfirmationStatusFilter initial checkin

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Extensions/ILinkGeneratorExtensionsTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Extensions/ILinkGeneratorExtensions.cs
Removed redundant code from ILinkGeneratorExtensions and ILinkGeneratorExtensionsTests
=> CON-4302 Removed redundant link generator extension methods

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenCallingResendEmailInvitationTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/ApprenticeshipDetailsRequestViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/ResendEmailInvitationRequest.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Shared/NotificationParameters.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/SFA.DAS.EmployerCommitmentsV2.Web.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/appsettings.Development.json
CS-1354-ResendInvitation-Employer
=> CS-1354-ResendInvitation-Employer

src/SFA.DAS.EmployerCommitmentsV2.Api.FakeServers/CommitmentsOuterApiBuilder.cs, src/SFA.DAS.EmployerCommitmentsV2.Api.FakeServers/MockApi.cs, src/SFA.DAS.EmployerCommitmentsV2.Api.FakeServers/Program.cs, src/SFA.DAS.EmployerCommitmentsV2.Api.FakeServers/SFA.DAS.EmployerCommitmentsV2.Api.FakeServers.csproj, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/CohortControllerTests/WhenIAddDraftApprenticeship.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/ApprenticeRequestToSelectCourseViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/ApprenticeRequestToSelectDeliveryModelViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/SelectCourseViewModelToApprenticeRequestMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Cohort/SelectDeliveryModelViewModelToApprenticeRequestMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/CohortController.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/ApprenticeRequestToSelectCourseViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/ApprenticeRequestToSelectDeliveryModelViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/ApprenticeViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/InformRequestToSelectTransferConnectionViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/SelectCourseViewModelToApprenticeRequestMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/SelectDeliveryModelViewModelToApprenticeRequestMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/ApprenticeRequest.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Shared/SelectCourseViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Shared/SelectDeliveryModelViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/SelectCourse.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/SelectDeliveryModel.cshtml, src/SFA.DAS.EmployerCommitmentsV2.sln, src/SFA.DAS.EmployerCommitmentsV2/SFA.DAS.EmployerCommitmentsV2.csproj, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/ApprovalsApiClient.cs, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/IApprovalsApiClient.cs, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/Responses/ProviderCourseDeliveryModels.cs
PA-202-AddSelectCourseAndDeliveryModelPages
=> PA-202-AddSelectCourseAndDeliveryModelPages

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Apprentice/ApprenticeshipDetailsRequestViewModel.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/EditApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/ApprovalsApiClient.cs, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/IApprovalsApiClient.cs, src/SFA.DAS.EmployerCommitmentsV2/Services/Approvals/Responses/GetApprenticeshipDetailsResponse.cs
Same implementation as we did on FJA-92
=> FJA-100 When Employer is non-FJAA, the delivery model is shown on Apprentice

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Models/CohortDraftApprenticeshipViewModelTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Cohort/DetailsViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Models/Cohort/CohortDraftApprenticeshipViewModel.cs
… an apprentice learner record
=> FLP-84 Employer: Actual start date must have been entered to able to approve an apprentice learner record

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_DraftApprenticeship.cshtml
… Provider should direct users to correct pages
=> FLP-108 Edit links on 'Add/Edit an apprentice' pages for Employer and Provider should direct users to correct pages

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ConfirmEditApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_DraftApprenticeship.cshtml
PA-510-IncludeConfirmationFilter
=> PA-510-IncludeConfirmationFilter

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ConfirmEditApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_DraftApprenticeship.cshtml
=> PA-457-AccessibilityChanges

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Shared/_DraftApprenticeship.cshtml
…he [Add/Edit] training details page
=> FLP-116 Navigate from the select standard & delivery model pages to the [Add/Edit] training details page

azure/template.json, src/SFA.DAS.EmployerCommitmentsV2.Web/Properties/launchSettings.json, src/SFA.DAS.EmployerCommitmentsV2.Web/Startup/MaMenuStartup.cs
Use resource environment name so URL is correctly built across environments
=> FAI-717 - Update to use resource environment name

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/PauseApprenticeship.cshtml
Reverts SkillsFundingAgency/das-employercommitments-v2#390
=> Revert "MAP-186 Fixed broken link on pause apprenticeship page "

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ApprenticeshipNeverStarted.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ApprenticeshipNotEnded.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ChangeStatus.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ConfirmStop.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/HasTheApprenticeBeenMadeRedundant.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/PauseApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ResumeApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/StopApprenticeship.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/WhyStopApprenticeship.cshtml
Contains changes from branches [MAP-143](https://github.com/SkillsFundingAgency/das-employercommitments-v2/tree/MAP-143_Accidental_Stop) and [MAP-184](https://github.com/SkillsFundingAgency/das-employercommitments-v2/tree/MAP-184_Accidental_Stop). 
[MAP-143]: https://skillsfundingagency.atlassian.net/browse/MAP-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MAP-184]: https://skillsfundingagency.atlassian.net/browse/MAP-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MAP-188 Added Zendesk page tags to edit apprenticeship status journeys 

src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapperTests.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapper.cs, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/Details.cshtml, src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/DetailsPartials/_ApprenticeshipStatus.cshtml
Ensure payment status is conditional on apprenticeship start and improve tag colours
=> Ensure payment status is conditional

src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/DetailsPartials/_PaymentsWithheldBanner.cshtml
FLP-976 update payment withheld banner id
=> FLP-976 Update div id for payments withhelp banner
